#!/usr/bin/env bash

LOCALTIME_PATH=/etc/localtime
ZONEINFO_PATH=/usr/share/zoneinfo

get_timezone() {
  realpath $LOCALTIME_PATH | rev | cut -d'/' -f1,2 | rev
}

get_timezones() {
  local region="$1"
  find $ZONEINFO_PATH/$region/* -print | rev | cut -d'/' -f1,2 | rev
}

get_regions() {
  find /usr/share/zoneinfo/ -maxdepth 1 -type d | rev | cut -d'/' -f1,2 | rev | sed 's/zoneinfo\///;/^[[:space:]]*$/d'
}

set_timezone() {
  local new_timezone_path="$1"
  ln -sf "$ZONEINFO_PATH/$new_timezone_path" $LOCALTIME_PATH
}

print_help() {
  cat<<END
timezone [OPTIONS]

OPTIONS:
  -a <region>     get all timezone in a region, e.g. Europe
  -c              get current timezone
  -s <timezone>   new timezone, e.g. Europe/Tallinn
  -r              get all regions
  -h              print this help
END
}

while getopts "cs:ha:r" opt; do
  case $opt in
    a) get_timezones "$OPTARG" ;;
    c) get_timezone            ;;
    h) print_help              ;;
    s) set_timezone "$OPTARG"  ;;
    r) get_regions             ;;
    *) print_help              ;;
  esac
done

[ -z "$1" ] && print_help

exit 0
