#!/bin/sh

suffix=BACKUP--`date +%Y-%m-%d-%H%M`

show_help() {
    cat << END_HELP
backup <file>...
END_HELP
}

[ $# -eq 0 ] && { show_help 1>&2; exit 1; };

for file; do
    echo "Copying $file to $file.$suffix"
    cp -p $file "$file.$suffix"
done

exit 0

