#!/bin/sh

[ $# -eq 0 ] && { echo "repeat <num> [char]" 1>&2; exit 1; }

char=#
[ $# -eq 2 ] && char="$2"

i=0
result=
while [ $i -ne $1 ]; do
    i=$((i + 1))
    result="$result$char"
done

echo "$result"
exit 0
